//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSENT
    {
        public string AbsentID { get; set; }
        public string AbsentName { get; set; }
        public Nullable<int> AbsentType { get; set; }
        public Nullable<int> MaxDay { get; set; }
    }
}
