//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVANCED
    {
        public string EmployeeID { get; set; }
        public System.DateTime DateAdvanced { get; set; }
        public int Value { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
