//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOWANCE
    {
        public string AllowanceID { get; set; }
        public string AllowanceName { get; set; }
        public bo//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    namespace HRM.Models
    {
        using System;
        using System.Collections.Generic;
        using System.ComponentModel.DataAnnotations;

        public partial class ALLOWANCE
        {
            public string AllowanceID { get; set; }
            [Required(ErrorMessage = "Vui lòng nhập tên trợ cấp/phụ cấp/thưởng.")]
            public string AllowanceName { get; set; }
            public bool Insurance { get; set; }
            public bool Tax { get; set; }
            [Range(0, int.MaxValue, ErrorMessage = "Phần miễn thuế phải lớn hơn hoặc bằng 0")]
            public Nullable<int> FreeTax { get; set; }
            [Range(0, int.MaxValue, ErrorMessage = "Giá trị phải lớn hơn hoặc bằng 0")]
            public Nullable<int> Value { get; set; }
        }
    }
    ol Insurance { get; set; }
        public bool Tax { get; set; }
        public Nullable<int> FreeTax { get; set; }
        public Nullable<int> Value { get; set; }
    }
}
