//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ALLOWANCE
    {
        public string AllowanceID { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên trợ cấp/phụ cấp/thưởng.")]
        public string AllowanceName { get; set; }
        public bool Insurance { get; set; }
        public bool FreeTax { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Phần miễn thuế phải lớn hơn hoặc bằng 0")]
        public Nullable<int> FreeTaxValue { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Giá trị phải lớn hơn hoặc bằng 0")]
        public int Value { get; set; }
    }
}
