//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONUSDETAIL
    {
        public string BonusID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> Value { get; set; }
    
        public virtual BONU BONU { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
