//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATEDETAIL
    {
        public string EmployeeID { get; set; }
        public string CertificateName { get; set; }
        public string TypeCertificateID { get; set; }
        public Nullable<System.DateTime> CertificateDate { get; set; }
        public string CertificatePlace { get; set; }
    
        public virtual CERTIFICATE CERTIFICATE { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
