//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDUCATIONDETAIL
    {
        public string EmployeeID { get; set; }
        public string EducationID { get; set; }
        public string MajorID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Place { get; set; }
    
        public virtual EDUCATION EDUCATION { get; set; }
        public virtual MAJOR MAJOR { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
