//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ADVANCED = new HashSet<ADVANCED>();
            this.ADVANCEDREPORT = new HashSet<ADVANCEDREPORT>();
            this.ALLOWANCEDETAIL = new HashSet<ALLOWANCEDETAIL>();
            this.ALLOWANCEREPORT = new HashSet<ALLOWANCEREPORT>();
            this.BONUSDETAIL = new HashSet<BONUSDETAIL>();
            this.BONUSREPORT = new HashSet<BONUSREPORT>();
            this.CERTIFICATEDETAIL = new HashSet<CERTIFICATEDETAIL>();
            this.EDUCATIONDETAIL = new HashSet<EDUCATIONDETAIL>();
            this.SHIFTDETAIL = new HashSet<SHIFTDETAIL>();
            this.INSURANCEREPORT = new HashSet<INSURANCEREPORT>();
            this.SALARYREPORT = new HashSet<SALARYREPORT>();
            this.TAXREPORT = new HashSet<TAXREPORT>();
            this.TIMEKEEPING = new HashSet<TIMEKEEPING>();
            this.TIMEKEEPINGREPORT = new HashSet<TIMEKEEPINGREPORT>();
            this.GR = new HashSet<GR>();
        }
    
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public byte[] Image { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Birthplace { get; set; }
        public string HomeTown { get; set; }
        public string Nation { get; set; }
        public string Id { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Ward { get; set; }
        public string Dictrict { get; set; }
        public string RoomID { get; set; }
        public string PositionID { get; set; }
        public string ContractID { get; set; }
        public string HealthInsurance { get; set; }
        public string HealthInsuranceID { get; set; }
        public string SocialInsuranceID { get; set; }
        public string DeductionPersonal { get; set; }
        public Nullable<int> DeductionDependent { get; set; }
        public string Street { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVANCED> ADVANCED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVANCEDREPORT> ADVANCEDREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALLOWANCEDETAIL> ALLOWANCEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALLOWANCEREPORT> ALLOWANCEREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONUSDETAIL> BONUSDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONUSREPORT> BONUSREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERTIFICATEDETAIL> CERTIFICATEDETAIL { get; set; }
        public virtual CONTRACT CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDUCATIONDETAIL> EDUCATIONDETAIL { get; set; }
        public virtual POSITION POSITION { get; set; }
        public virtual ROOM ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIFTDETAIL> SHIFTDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSURANCEREPORT> INSURANCEREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALARYREPORT> SALARYREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAXREPORT> TAXREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMEKEEPING> TIMEKEEPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMEKEEPINGREPORT> TIMEKEEPINGREPORT { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GR> GR { get; set; }
    }
}
