//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ADVANCEDs = new HashSet<ADVANCED>();
            this.ALLOWANCEDETAILs = new HashSet<ALLOWANCEDETAIL>();
            this.INSURANCEREPORTs = new HashSet<INSURANCEREPORT>();
            this.SALARYREPORTs = new HashSet<SALARYREPORT>();
            this.TAXREPORTs = new HashSet<TAXREPORT>();
            this.TIMEKEEPINGREPORTs = new HashSet<TIMEKEEPINGREPORT>();
            this.SHIFTDETAILs = new HashSet<SHIFTDETAIL>();
            this.TIMEKEEPINGs = new HashSet<TIMEKEEPING>();
        }
    
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Sex { get; set; }
        public System.DateTime DoB { get; set; }
        public string Birthplace { get; set; }
        public string HomeTown { get; set; }
        public string Nation { get; set; }
        public string Id { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Ward { get; set; }
        public string Dictrict { get; set; }
        public string RoomID { get; set; }
        public string PositionID { get; set; }
        public string ContractID { get; set; }
        public bool FreeInsurance { get; set; }
        public string HealthInsuranceID { get; set; }
        public bool SelfDeduction { get; set; }
        public int DependentDeduction { get; set; }
        public string Street { get; set; }
        public Nullable<bool> State { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVANCED> ADVANCEDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALLOWANCEDETAIL> ALLOWANCEDETAILs { get; set; }
        public virtual CERTIFICATEDETAIL CERTIFICATEDETAIL { get; set; }
        public virtual CONTRACT CONTRACT { get; set; }
        public virtual EDUCATIONDETAIL EDUCATIONDETAIL { get; set; }
        public virtual POSITION POSITION { get; set; }
        public virtual ROOM ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSURANCEREPORT> INSURANCEREPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALARYREPORT> SALARYREPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAXREPORT> TAXREPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMEKEEPINGREPORT> TIMEKEEPINGREPORTs { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIFTDETAIL> SHIFTDETAILs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMEKEEPING> TIMEKEEPINGs { get; set; }
    }
}
