//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hrmserver_HRMEntities : DbContext
    {
        public hrmserver_HRMEntities()
            : base("name=hrmserver_HRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABSENT> ABSENT { get; set; }
        public virtual DbSet<ADVANCED> ADVANCED { get; set; }
        public virtual DbSet<ADVANCEDREPORT> ADVANCEDREPORT { get; set; }
        public virtual DbSet<ALLOWANCE> ALLOWANCE { get; set; }
        public virtual DbSet<ALLOWANCEDETAIL> ALLOWANCEDETAIL { get; set; }
        public virtual DbSet<ALLOWANCEREPORT> ALLOWANCEREPORT { get; set; }
        public virtual DbSet<BONUS> BONUS { get; set; }
        public virtual DbSet<BONUSDETAIL> BONUSDETAIL { get; set; }
        public virtual DbSet<BONUSREPORT> BONUSREPORT { get; set; }
        public virtual DbSet<CERTIFICATE> CERTIFICATE { get; set; }
        public virtual DbSet<CERTIFICATEDETAIL> CERTIFICATEDETAIL { get; set; }
        public virtual DbSet<CONTRACT> CONTRACT { get; set; }
        public virtual DbSet<DATEINFORMATION> DATEINFORMATION { get; set; }
        public virtual DbSet<EDUCATION> EDUCATION { get; set; }
        public virtual DbSet<EDUCATIONDETAIL> EDUCATIONDETAIL { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<GR> GR { get; set; }
        public virtual DbSet<GROUPPERMISSION> GROUPPERMISSION { get; set; }
        public virtual DbSet<INSURANCEREPORT> INSURANCEREPORT { get; set; }
        public virtual DbSet<MAJOR> MAJOR { get; set; }
        public virtual DbSet<PARAMETER> PARAMETER { get; set; }
        public virtual DbSet<PERMISSION> PERMISSION { get; set; }
        public virtual DbSet<POSITION> POSITION { get; set; }
        public virtual DbSet<ROOM> ROOM { get; set; }
        public virtual DbSet<SALARYREPORT> SALARYREPORT { get; set; }
        public virtual DbSet<SHIFT> SHIFT { get; set; }
        public virtual DbSet<SHIFTDETAIL> SHIFTDETAIL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TAXRATE> TAXRATE { get; set; }
        public virtual DbSet<TAXREPORT> TAXREPORT { get; set; }
        public virtual DbSet<TIMEKEEPING> TIMEKEEPING { get; set; }
        public virtual DbSet<TIMEKEEPINGREPORT> TIMEKEEPINGREPORT { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
