//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCEREPORT
    {
        public System.DateTime Month { get; set; }
        public string EmployeeID { get; set; }
        public int InsurancePaySalary { get; set; }
        public int SocialInsurancePay { get; set; }
        public int HealthInsurancePay { get; set; }
        public int TotalInsurancePay { get; set; }
        public int WorkInsurancePay { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
