//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCEREPORT
    {
        public System.DateTime Month { get; set; }
        public string EmployeeID { get; set; }
        public int InsurancePaySalary { get; set; }
        public int PersonalSocialInsurancePay { get; set; }
        public int PersonalHealthInsurancePay { get; set; }
        public int PersonalWorkInsurancePay { get; set; }
        public int BusinessSocialInsurancePay { get; set; }
        public int BusinessHealthInsurancePay { get; set; }
        public int BusinessWorkInsurancePay { get; set; }
        public int UnionFee { get; set; }
        public int PersonalInsurancePay { get; set; }
        public int BusinessInsurancePay { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
