//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAXREPORT
    {
        public System.DateTime Month { get; set; }
        public string EmployeeID { get; set; }
        public int TotalIncome { get; set; }
        public int SelfDeduction { get; set; }
        public int DependentDeduction { get; set; }
        public int OverTimeHour { get; set; }
        public int TaxableOverTime { get; set; }
        public int TaxableIncome { get; set; }
        public int IncomeTax { get; set; }
        public int AssessableIncome { get; set; }
        public int OverTimeSalary { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
