//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMEKEEPING
    {
        public System.DateTime Date { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> HoursWorkDay { get; set; }
        public Nullable<int> HoursWorkNight { get; set; }
        public string ShiftID { get; set; }
    
        public virtual DATEINFORMATION DATEINFORMATION { get; set; }
        public virtual SHIFT SHIFT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
