//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMEKEEPINGREPORT
    {
        public System.DateTime Month { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> SumWorkDay { get; set; }
        public Nullable<int> SumLateDay { get; set; }
        public Nullable<int> SunAbsentNoSalary { get; set; }
        public Nullable<int> SumVacation { get; set; }
        public Nullable<int> SumAbsent { get; set; }
        public Nullable<int> SumHourNormal { get; set; }
        public Nullable<int> SumHourDayOff { get; set; }
        public Nullable<int> SumHourVacation { get; set; }
        public Nullable<int> SumHourNight { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
