//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMEKEEPINGREPORT
    {
        public System.DateTime Month { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> SumWorkDay { get; set; }
        public Nullable<int> SumAbsentHaveSalary { get; set; }
        public Nullable<int> SumAbsentNoSalary { get; set; }
        public Nullable<int> SumHourNormal { get; set; }
        public Nullable<int> SumHourDayOff { get; set; }
        public Nullable<int> SumHourSpecialDayOff { get; set; }
        public Nullable<int> SumHourNightNormal { get; set; }
        public Nullable<int> SumHourNightDayOff { get; set; }
        public Nullable<int> SumHourNightSpecialDayOff { get; set; }
        public Nullable<int> SumHourNightNormalExtra { get; set; }
        public Nullable<int> SumHourNightDayOffExtra { get; set; }
        public Nullable<int> SumHourNightSpecialDayOffExtra { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
